// Auto-generated by autism-research-monitor scheduled task
// Do not edit manually — this file is overwritten on each scan run
window.CLINICAL_FEED = {
  last_updated: "2026-04-04",
  trials: [
    // Each trial entry looks like:
    // {
    //   id: "NCT06123456",
    //   title: "Phase 2 Study of XYZ in Rett Syndrome",
    //   condition: "Rett Syndrome",
    //   intervention: "XYZ-101 (oral, twice daily)",
    //   phase: "Phase 2",
    //   status: "RECRUITING",      // RECRUITING | NOT_YET_RECRUITING | ACTIVE_NOT_RECRUITING | COMPLETED
    //   sponsor: "Company Name",
    //   enrollment: 60,
    //   start_date: "2026-01-15",
    //   completion_date: "2027-06-30",
    //   genes_relevant: ["MECP2"],
    //   track: 4,                  // 1-4 research track
    //   relevance: "CRITICAL",     // CRITICAL | HIGH | MEDIUM
    //   summary: "One-line relevance summary",
    //   url: "https://clinicaltrials.gov/study/NCT06123456"
    // }
  ],
  papers: [
    // Research monitor also finds papers across 4 tracks
    // Same format as papers_feed.js entries, plus:
    // track: 1-4
    // relevance: "CRITICAL" | "HIGH" | "MEDIUM"
  ]
};
