// Auto-generated by atlas-daily-scan scheduled task
// Do not edit manually — this file is overwritten on each scan run
window.PAPERS_FEED = {
  last_updated: "2026-04-04",
  papers: [
    // Each paper entry looks like:
    // {
    //   id: "PMID_12345678",
    //   title: "Paper title here",
    //   authors: "First A, Last B",
    //   journal: "Nature Neuroscience",
    //   date: "2026-04-01",
    //   source: "pubmed",          // pubmed | biorxiv | medrxiv
    //   score: 32,                 // 0-50 relevance score
    //   decision: "INTEGRATE",     // INTEGRATE | REVIEW | SKIP
    //   genes_mentioned: ["SCN2A", "MECP2"],
    //   summary: "One-line summary of why this matters",
    //   doi: "10.1038/s41586-026-00000-0",
    //   url: "https://pubmed.ncbi.nlm.nih.gov/12345678/"
    // }
  ]
};
